# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16yotnBR1G2RaMSP5bBEX04NZyq8UJCHr
"""

#1
length= float(input("enter the length"))
width = float(input("enter the width"))
area = length*width
print("area of a rectangle is ",area)

#2
weight = float((input("enter the weight in kg")))
height = float((input("enter the height in m")))
bmi = weight/(height*height)
print("Your Bmi is ",bmi)

#3
student={
    "alex":100,"aravind":100,"hema":80,"lucy":75
}
print("student name with scores")
print(student)

#4
name = str(input("enter the name"))
age  = int(input("enter the age"))

if(age<18):
  print(name,"is minor")
elif(age>=18 and age<60):
  print(name,"is adult")
elif(age>=60):
  print(name,"is senior")
else:
  print("print proper age")

#5
for i in range(1,50):
  if(i%2==0):
    print(i,"is a even number")

#6
password = "12345"
flag=0
while(flag==0):
  verifypass = str(input("enter the password"))
  if(password==verifypass):
      print("password is correct")
      flag=1
      break
  else:
    print("enter the correct password")
    flag=0

#7

def avg(numberslist):
  countofnumbers = len(numberslist)
  sum=0
  for i in numberslist:
    sum+=i
  average = sum/countofnumbers
  print("average of list of numbers is ",average)


numberslist = [2,4,5,7,8,9,11]
avg(numberslist)

#8
userinput = str(input("enter the input string"))
vowellist = ['a','e','i','o','u','A','E','I','O','U']
vowelcount =0
for i in userinput:
  if i in vowellist:
    vowelcount+=1
print("vowel count in string is ",vowelcount)

#9
import datetime
print("current date and time is ",datetime)

#10
value1 = 10
value2 = "a"
sum=0
try:
  sum = value1 + value2
except TypeError:
  print("Type error")

#11
try:
  def valueerr(**val1):
    print (val1)
except ValueError:
  print("print appropriate argument value")

valueerr(mother=3,son=2,brother=1)

#12
value1 = 10
value2 = 0
div=0
try:
 div= value1/value2
except ZeroDivisionError:
  print("denominator cannot be zero")

#13

sentence = "Hello python!"
var_write = open("C:\Users\Downloads\python.txt","w")
var_write.write(sentence)

#14
var_read = open("C:\Users\Downloads\sql1.sql","r")
print(var_read.read)

#15
appstring = "hi python"
var_append = open("C:\Users\Downloads\python.txt")
var_append.append(appstring)
var_read = open("C:\Users\Downloads\python.txt")
var_read.read